# Generated by Django 3.1.3 on 2021-05-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-modified',), 'verbose_name_plural': 'Pagamentos'},
        ),
    ]
