# Generated by Django 3.1.3 on 2021-05-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210509_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Noticias'},
        ),
    ]
