# Generated by Django 3.1.3 on 2021-05-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210513_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name_plural': 'Favoritos'},
        ),
    ]
