# Generated by Django 3.1.3 on 2021-05-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('topico', models.CharField(max_length=100)),
                ('numero_questoes', models.IntegerField()),
                ('tempo', models.IntegerField(help_text='duração em minutos')),
                ('dificuldade', models.CharField(max_length=250, verbose_name=(('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Dificil', 'Dificil')))),
            ],
        ),
    ]
