# Generated by Django 3.1.3 on 2021-05-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20210510_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='dificuldade',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Dificil', 'Dificil')], max_length=250),
        ),
    ]
