# Generated by Django 3.1.3 on 2021-05-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_auto_20210510_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='porcentagem_necessaria',
            field=models.IntegerField(blank=True, default=0, help_text='Porcentagem necessária para passar', null=True),
        ),
    ]
