# Generated by Django 3.1.3 on 2021-05-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_quiz_porcentagem_necessaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Pode ser nula', null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.categoria'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='tempo',
            field=models.IntegerField(help_text='duração em minutos do quiz'),
        ),
    ]
