# Generated by Django 3.1.3 on 2021-05-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210216_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Ordens'},
        ),
    ]
